from segment_colonies_cellpose import segment_well_colonies as segment_cellpose
from segment_colonies_mixed import segment_well_colonies_hybrid
from segment_colonies_threshold import segment_well_colonies as segment_thesh